---
  - name: Create AWS VPC
    hosts: localhost
    connection: local
    gather_facts: no
    vars:
       aws_access_key: ''
       aws_secret_key: ''
       ec2_ansible_group: "{{ user_name }}"
       ec2_security_group_name: "{{vpc_name}}_SECGRP"
       ec2_vpc_subnet_name: "{{vpc_name}}_Subnet"
       ec2_rt_name: "{{vpc_name}}_RT_Internet"
       ec2_igw_name: "{{vpc_name}}_IGW"
       my_email_address: "{{user_name}}@redhat.com"


    tasks:
    - name: 'Preflight Varible check :: aws_access_key'
      fail: msg='Please include the aws_access_key to the variable "aws_access_key"'
      run_once: true
      when: 'aws_access_key is not defined'
    - name: 'Preflight Varible check :: aws_secret_key'
      fail: msg='Please include the aws_secret_key to the variable "aws_secret_key"'
      run_once: true
      when: 'aws_secret_key is not defined'
    - name: 'Preflight Varible check :: vpc_name'
      fail: msg='Please include the vpc_name to the variable "vpc_name"'
      run_once: true
      when: 'vpc_name is not defined'
    - name: 'Preflight Varible check :: vpc_cidr'
      fail: msg='Please include the vpc_cidr to the variable "vpc_cidr"'
      run_once: true
      when: 'vpc_cidr is not defined'
    - name: 'Preflight Varible check :: region'
      fail: msg='Please include the region to the variable "region"'
      run_once: true
      when: 'region is not defined'
    - name: 'Preflight Varible check :: user_name'
      fail: msg='Please include the user_name to the variable "user_name"'
      run_once: true
      when: 'user_name is not defined'
    - name: 'Preflight Varible check :: alwaysup'
      fail: msg='Please include the alwaysup to the variable "alwaysup"'
      run_once: true
      when: 'alwaysup is not defined'
    - name: 'Preflight Varible check :: deleteby'
      fail: msg='Please include the deleteby to the variable "deleteby"'
      run_once: true
      when: 'deleteby is not defined'
   # Gather the start time to use in a later playbook
    - name: Record the vpc start time
      ansible.builtin.command:
        cmd: "date '+%H:%M:%S'"
      delegate_to: 127.0.0.1
      register: vpc_create_time_pre
      run_once: true

# Make the start time available to other playbooks
    - name: Capture the create vpc_create_time
      ansible.builtin.set_stats:
         data:
           vpc_create_time: "{{ vpc_create_time_pre.stdout }}"
      run_once: true



    - name: Create VPC {{ vpc_name }}_{{user_name}} in {{ region }}
      amazon.aws.ec2_vpc_net:
        name: "{{ vpc_name }}_{{user_name}}"
        cidr_block: "{{ vpc_cidr }}"
        region: "{{ region }}"
        state: present

        tags:
          AlwaysUp: "{{alwaysup}}"
          Name: "{{user_name}}"
          ansible_group: "{{ec2_ansible_group}}"
          Createdby: Ansible Controller
          Contact: "{{my_email_address}}"
          DeletebBy: "{{deleteby}}"
      register: my_vpc
    - name: Display my_vpc.vpc.id info for "{{vpc_name}}"
      debug:
        var: my_vpc.vpc.id

    - name: create security group {{ ec2_security_group_name }}
      amazon.aws.ec2_group:
        name: "{{ ec2_security_group_name }}"
        description: Security group with rule descriptions created by Ansible
        vpc_id: "{{ my_vpc.vpc.id }}"
        region: "{{ region }}"
        tags:
          AlwaysUp: "{{ alwaysup }}"
          Name: "{{ user_name }}"
          ansible_group: "{{ ec2_ansible_group }}"
          Createdby: Ansible Controller
          Contact: "{{ my_email_address }}"
          DeleteBy: "{{deleteby}}"
        rules:
        - proto: icmp
          from_port: 8 # icmp type, -1 = any type
          to_port:  -1 # icmp subtype, -1 = any subtype
          cidr_ip: 0.0.0.0/0
          rule_desc: allow ping
        - proto: tcp
          ports: 80
          cidr_ip: 0.0.0.0/0
          rule_desc: allow all on port 80
        - proto: tcp
          ports: "{{ open_ports_list }}"
          cidr_ip: 0.0.0.0/0
          rule_desc: allow all on port {{open_ports_list}}
        - proto: tcp
          ports: 3306
          cidr_ip: 10.100.100.0/24
          rule_desc: allow DB on port 3306

      tags:
        - createsecgrp
        - onlyvpc
      register: my_security_group
    - name: Create {{ ec2_vpc_subnet_name }} subnet
      amazon.aws.ec2_vpc_subnet:
        state: present
        vpc_id: "{{ my_vpc.vpc.id }}"
        cidr: "{{ vpc_cidr }}"
        region: "{{ region }}"
        map_public: yes
        tags:
          AlwaysUp: "{{alwaysup}}"
          Name: "{{ ec2_vpc_subnet_name }}"
          ansible_group: "{{ ec2_ansible_group }}"
          Createdby: Ansible Controller
          Contact: "{{ my_email_address }}"
          DeleteBy: "{{deleteby}}"
      tags:
        - createsubnet
        - onlyvpc
      register: my_vpc_subnet
    - name: Create IGW "{{ ec2_igw_name }}" for {{ vpc_name }}_{{user_name}}
      amazon.aws.ec2_vpc_igw:
        vpc_id: "{{ my_vpc.vpc.id }}"
        region: "{{ region }}"
        state: present
        tags:
          Name: "{{ec2_igw_name}}"
          ansible_group: "{{ ec2_ansible_group }}"
          Createdby: Ansible Tower
          Contact: "{{my_email_address}}"
          DeletebBy: "{{deleteby}}"
      tags:
        - createigw
        - onlyvpc
      register: my_igw
    #- name: Gather default Route Table ID
    #  ec2_vpc_route_table_info:
    #    region: "{{ region }}"
    #    filters:
    #      vpc-id: "{{ my_vpc.vpc.id }}"
    #  register: vpc_default_route

    - name: Create Internet route Table "{{ec2_rt_name}}"
      amazon.aws.ec2_vpc_route_table:
        vpc_id: "{{ my_vpc.vpc.id }}"
        region: "{{ region }}"
        #route_table_id: "{{ vpc_default_route.route_tables[0].id }}"
        #lookup: id
        tags:
          AlwaysUp: " {{alwaysup}} "
          Name: "{{ ec2_rt_name }}"
          ansible_group: "{{ ec2_ansible_group }}"
          Createdby: Ansible Controller
          Contact: "{{ my_email_address }}"
          DeleteBy: "{{deleteby}}"
        subnets:
          - "{{ my_vpc_subnet.subnet.id }}"
        routes:
          - dest: 0.0.0.0/0
            gateway_id: "{{ my_igw.gateway_id }}"
      tags:
        - creatert
        - onlyvpc
      register: my_route_table
